### PR TITLE
E2 Reload bug

### LINKED ISSUE #20: Old DFrame persists when updating E2
When updating an existing E2, the Dframe does not get reset/deleted.

Code:
```
@name Persistent DFrame Bug
@persist Frame:dframe

if(first()) {
    runOnChat(1)
    Frame = dframe(1)
    Frame:makePopup()
    #Frame:setDeleteOnClose(0) # does not matter for this
    Frame:create()
    
    timer("hide",2000)
}elseif(chatClk()) {
    Frame:setVisible(1)
    Frame:modify()
}elseif(clk("hide")) {
    Frame:setVisible(0)
    Frame:modify()
}
```
1. Spawn E2
2. Move DFrame a bit and wait for it to close
3. Update E2 (Leftclick it again) -> No panel pops up this time
4. Type stuff in chat -> Old panel pops up at old position

Current Workaround: Remove old E2 and spawn again

### PR DESCRIPTION
**Pull request by Linus045**
This should fix #20  the reload bug.
We use a newly generated ID everytime we reload the E2 instead of the EntityID which caused problems with persistent panels.

TODO:

- [x] Make sure vehicle linking works
- [x] Test in multiplayer
- [x] TODOs in Code

### CODE REVIEW

File: lua/autorun/server/vguiCore.lua [hunk 1]
```diff
@@ -958,6 +957,26 @@ end)
...
+--             entity:GetOwner().e2_vgui_core_default_players[entity:EntIndex()] = nil
+--         end
+    end)
+    registerCallback("construct", function(self)
+        -- give each e2 a random session id (was originally e2EntityID)
+        -- this identifier prevents problems when reloading the same e2 (because it used the same identifier for the panels)
+        -- when reloading we tell all clients to remove the old panels (see e2 "destruct" callback above)
+        -- and then generate a new session_id (here in the e2 "construct" event) which is used to identify panels for the reloaded e2
+        -- any events from the old e2 code (panel removal/closing, button clicks, etc.) will be ignored for the new e2 session
+        self.entity.e2_vgui_core_session_id = math.floor(math.Rand(0, 1000000))
```
Comment (Linus045) [inline lua/autorun/server/vguiCore.lua:977]: Validate that there is no other e2 spawned with the same e2_vgui_core_session_id.
Although its really unlikely, adding a simple check that goes through all e2 entities should be too big of an overhead, considering this only runs when the e2 gets spawned/reloaded.

Otherwise maybe add a global list that keeps track of all used ids?

Comment (Linus045) [reply lua/autorun/server/vguiCore.lua]: solved via `E2VguiCore.sessionIDToE2Entity` list
